contentDir = "content"

[module]
  [[module.imports]]
    path = "github.com/lxndrblz/anatole"
    disable = false

[related]
  includeNewer = true
  threshold = 80
  toLower = true
  [[related.indices]]
    name = 'keywords'
    weight = 100
  [[related.indices]]
    name = 'tags'
    weight = 80

[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"