author = "Ann Nguyen"
description = """
ANN NGUYEN
My official blog where I
muse on tech, leadership and society.
"""
customCss = ["css/custom.css"]
profilePicture = "images/ann-square.jpg"
contentratio = 0.7
pygmentsCodeFences = true
pygmentsUseClasses = true

# Content Settings
mainSections = ["post"]
readMore = true
relatedPosts = true
numberOfRelatedPosts = 3

## Math settings
[math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

[[socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://linkedin.com/in/annthinguyen"

[[socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/annnguyen"
